### PR TITLE
Add kwargs to arguments

### LINKED ISSUE #25: Add  **kwargs to low level functions
The same attributes are being from all the functions ( data, strata etc), by adding the **kwargs to all level functions we can pass the inputs of the high level function to low level functions.

### PR DESCRIPTION
**Pull request by AntonZogk**
# Summary

Add kwargs to low levels functions, this will allow passing a dictionary to them to avoid attribute repetitions in the top level function 
# Checklists

This pull request meets the following requirements:

- [x] installable with all dependencies recorded
- [x] runs without error
- [x] follows PEP8 and project specific conventions
- [x] appropriate use of comments, for example no descriptive comments
- [ ] functions documented using Numpy style docstings
- [x] assumptions and decisions log considered and updated if appropriate
- [x] unit tests have been updated to cover essential functionality for a reasonable range of inputs and conditions
- [x] other forms of testing such as end-to-end and user-interface testing have been considered and updated as required
- [x] tests suite passes (locally as a minimum)
- [ ] peer reviewed with review recorded

If you feel some of these conditions do not apply for this pull request, please
add a comment to explain why.
Closes #25

### CODE REVIEW

**Comment by lhubbardONS** [comment]
All tests and pre-commit hooks run successfully. Outside of src/flag_and_count_matched_pairs.py, all functions with kwargs seem to be missing kwargs in their docstrings - should this be included?

**Comment by AntonZogk** [comment]
> All tests and pre-commit hooks run successfully. Outside of src/flag_and_count_matched_pairs.py, all functions with kwargs seem to be missing kwargs in their docstrings - should this be included?

You are right @lhubbardONS, i have committed the docstrings.

**Review by lhubbardONS — APPROVED** [review]
Thanks Anton! I can see create_impute_flags (in imputation_flags.py) is still missing a kwargs entry in the docstring. Approving now and happy for this to be merged once added. :)

**Comment by AntonZogk** [comment]
@lhubbardONS Thanks for spotting these :)

**Pull request merged**
